# Generated by Django 6.0.2 on 2026-02-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=200)),
                ('Intro', models.CharField(max_length=1000)),
                ('head1', models.CharField(max_length=500)),
                ('Chead1', models.CharField(max_length=2000)),
                ('head2', models.CharField(max_length=500)),
                ('Chead2', models.CharField(max_length=2000)),
                ('head3', models.CharField(max_length=500)),
                ('Chead3', models.CharField(max_length=2000)),
                ('p_date', models.DateTimeField()),
            ],
        ),
    ]
